"""empty message

Revision ID: 86c866c1d975
Revises: e2f78e2df032
Create Date: 2023-11-21 02:40:17.687386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c866c1d975'
down_revision = 'e2f78e2df032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
